version: 0.3.0.{build}
image: Visual Studio 2019

configuration:
- Release
- Debug

platform: Any CPU

before_build:
  - nuget restore

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build:
  project: .\Checkouts-Overview.sln
  verbosity: minimal

for:
  -
    matrix:
      only:
        - configuration: Release
    after_build:
    - ps: .\publish-release.ps1 -version $env:APPVEYOR_BUILD_VERSION
    artifacts:
    - path: .\bin\Release\Checkouts-Overview*.zip
      name: Checkouts-Overview
