version: 0.3.1.{build}
image: Visual Studio 2019

configuration:
- Release
- Debug

platform: Any CPU

before_build:
  - nuget restore

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build:
  project: .\Checkouts-Overview.sln
  verbosity: minimal

test_script:
- cmd: nuget install Appveyor.TestLogger -Version 2.0.0
- cmd: dotnet test --no-build --no-restore --test-adapter-path:. --logger:Appveyor Test

for:
  -
    matrix:
      only:
        - configuration: Release
    after_build:
    - ps: .\app\publish-release.ps1 -version $env:APPVEYOR_BUILD_VERSION
    artifacts:
    - path: .\app\bin\Release\Checkouts-Overview*.zip
      name: Checkouts-Overview
